export const equipmentSlots = [
	'arm1',
	'arm1',
	'arm3',
	'acc1',
	'acc2',
	'acc3',
	'acc4',
	'acc5'
];

export const accessoryStats = {
	thickPaint : {
		name: 'Thick Paint',
		description: 'Poor workmanship has its upsides.',
		potency: 1,
		Durability: 1,
	},
	antenna : {
		name: 'Antenna',
		description: 'A thin metal rod and old chewing gum.',
		potency: 3,
		ScanDistance: 1,
	},
	minorShieldBooster : {
		name: 'Minor Shield Booster',
		description: 'Attachment that reroutes energy to your shield.',
		potency: 1,
		Shield: 1,
		Capacitor: -5,
	},
	plateCoat : {
		name: 'Plate Coat',
		description: 'A coat of metal to protect metal...',
		potency: 1,
		Armor: 1,
		MovementCost: 2,
	},
	solderingNanobots: {
		name: 'Soldering Nanobots',
		description: 'Miniscule metal miracle workers.',
		potency: 3,
		AutoRepair: .1,
	},
	batteryPack: {
		name: 'Battery Pack',
		description: 'Ghetto add-on to aid with energy "production".',
		potency: 3,
		Reactor: 1,
	},
	powerGlove: {
		name: 'Power Glove',
		description: "Now you're swinging with power!",
		potency: 5,
		Power: 2,
	},
	wd40 : {
		name: "WD-40",
		description: "Mistaken for a lubricant, but it works...",
		potency: 1,
		MovementCost: -2,
	},
	weldOnGenerator : {
		name: "Weld-on Generator",
		description: "Weld-on, weld-off.",
		potency: 6,
		Reactor: 2,
	},
	laserSight : {
		name: "Laser Sight",
		description: "Weak beam of energy that aids in gauging trajectories.",
		potency: 2,
		Accuracy: 1,
	},
	powerThimble : {
		name: "Power Thimble",
		description: "Lesser known 80's peripheral.",
		potency: 2,
		Power: 1,
	},
	coldFusionCell : {
		name: "Cold Fusion Cell",
		description: "Extraordinarily unlikely milestone of energy transference!",
		Reactor: 4,
		potency: 9,
	},
	hudEnhancement : {
		name: "HUD Enhancement",
		description: "Hardware that contains software that can't be firmware.",
		potency: 5,
		Accuracy: 2,
	},
	resistanceModulator : {
		name: "Resistance Modulator",
		description: "State-of-the-art R.E. mod - it's in the name.",
		potency: 2,
		ScanCost: -1,
		aimCostModifier: -1,
	},
	titaniumShell : {
		name: "Titanium Shell",
		description: "Melchoir is proud of its anodized polychromatism.",
		potency: 7,
		Armor: 5,
		MovementDistance: -1,
	},
	forceField : {
		name: "Force Field",
		description: "The future is now old man.",
		potency: 7,
		Shield: 5,
		Capacitor: -15,
	},
	hydraulicExoskeleton : {
		name: "Hydraulic Exoskeleton",
		description: "What every young robot wants for their assemblyday",
		potency: 8,
		Power: 2,
		Durability: 3,
	},
	liquidMetalCoating : {
		name: "Liquid Metal Coating",
		description: "Tattoo removal is a walk in the park.",
		potency: 4,
		Armor: 1,
		Durability: 4,
	},
	kevlarInsulation : {
		name: "Kevlar Insulation",
		description: "Whatever takes the edge off.",
		potency: 5,
		DamageReduction: 1,
	},
	hypersonicReverberator : {
		name: "Hypersonic Reverberator",
		description: "Pinpoints anomalous density points prone to failure.",
		potency: 5,
		DamageBonus: 2,
	},
	rocketPropulsion : {
		name: "Rocket Propulsion",
		description: "Fear is for those with flesh.",
		potency: 5,
		Movement: 1,
		CollisionDamageMultiplier: 1.25,
	},
	martialArtsEnhancementKit : {
		name: "Martial Arts Enhancement Kit",
		description: "Now you know kung fu, for now.",
		potency: 6,
		MeleeDamageMultiplier: 1.1,
		MeleeDamageReductionMultiplier: 1.1,
	},
}

export const weaponStats = {
	Gun1: {
		name: "Pewpew",
		description: "Handgun of questionable efficacy and naming.",
		damage: 8,
		superTypes: ['Ranged'],
		subTypes: ['Piercing', 'Accuracy'],
		projectileSpeed: 4,
		attackShape: 'line',
		reloadTime: 2,
		attackCost: 20,
		aimCost: 5,
		potency: 1,
	},
	Sword1: {
		name: "Busted Sword",
		description: "A sword that was once great.",
		damage: 11,
		superTypes: ['Melee'],
		subTypes: ['Piercing', 'Power'],
		attackShape: 'adjacentCell',
		attackCost: 20,
		potency: 1,
	},
	Hammer1: {
		name: "Bambam",
		description: "Primitive doesn't always mean inferior.",
		damage: 13,
		superTypes: ['Melee'],
		subTypes: ['Crushing', 'Power'],
		attackShape: 'adjacentCell',
		attackCost: 25,
		potency: 2,
	}
}
export const attackShapes = {
	adjacentCell : [
		null, null, null, null, null, null,
		null, null, null, null, null, null,
		null, 'violet', null, null, null, null,
		null, null, 'lime', 'red', null, null,
		null, null, null, null, null, null,
		null, null, null, null, null, null,
	],
	line : [
		null, null, null, null, null, null,
		null, null, null, null, null, null,
		null, null, null, null, 'red', 'red',
		null, null, 'red', 'red', null, null,
		null, 'lime', 'violet', 'violet', 'violet', 'violet',
		null, null, null, null, null, null,
	],
	cone : [
		null, null, null, null, null, null,
		null, 'violet', null, null, null, null,
		null, 'violet', 'violet', 'lime', null, null,
		null, 'violet', null, null, 'red', 'red',
		null, null, null, null, 'red', 'red',
		null, null, null, null, null, null,
	]
}