const tips = [
	"IF ALL OF YOUR BOTS ARE DESTROYED, YOU LOSE - EVEN IF ALL HOSTILES HAVE BEEN DESTROYED",
	"A BOT IS CONSIDERED DESTROYED ONCE ITS DURABILITY REACHES 0",
	"COMPLETE A LEVEL OR CHALLENGE BY DESTROYING ALL HOSTILES AND HAVING MORE THAN 0 DURABILITY",
	"COMPLETING A LEVEL FOR THE FIRST TIME WILL UNLOCK THE NEXT LEVEL!",
	"EVERY 5 LEVELS COMPLETED WILL UNLOCK A GAMBIT CHALLENGE",
	"EVERY 20 LEVELS COMPLETED WILL UNLOCK A GAUNTLET CHALLENGE",
	"EVERY 100 LEVELS COMPLETED WILL UNLOCK A GOD CHALLENGE",
	"EVERY LEVEL AND CHALLENGE HAS 3 REWARDS TO BE COLLECTED BY MEETING SPECIFIC CRITERIA",
	"LOOK AT THE HISTORY TAB FOR WHAT REWARDS ARE TO BE GAINED FROM EACH LEVEL AND CHALLENGE",
	"CHALLENGES PROVIDE MORE POTENT REWARDS",
	"COMPLETE LEVELS WITH ALL YOUR BOT MODELS TO COLLECT MORE GOLD STARS TO BE SPENT ON TECHS",
	"BUILDING LEVEL SPECIFIC AIS MAY TEMPT YOU, BUT IT IS LIKELY A BAD LONG TERM STRATEGY",
	"NOT ALL AI STRATEGIES ARE VIABLE ON EVERY LEVEL",
	"CHALLENGES WILL RUN YOUR BOT(S) THROUGH MULTIPLE LEVELS, WITH NO REST BETWEEN THEM",
	"MELEE WEAPONS DEAL MORE DAMAGE PER ENERGY SPENT THAN EQUAL LEVELED RANGED WEAPONS",
	"FIRE DAMAGE CAUSES RECURRING, BUT DWINDLING, BURN DAMAGE EACH TICK",
	"ACID DAMAGE CAUSES CORROSION AND DECREASES THE RECIPIENT'S ARMOR",
]

export default tips;