const goalsInfo = {
	requirements: {
		pre : {
			BESTFRIENDS: 'EMERGE VICTORIOUS WITHOUT ANY OF YOUR ALLIES BEING DESTROYED',
			BUSHIDO: 'EMERGE VICTORIOUS HAVING ONLY DEALT MELEE DAMAGE',
			GOLDENSTANDARD: 'EMERGE VICTORIOUS WITHOUT TAKING DAMAGE',
			GUTS: 'EMERGE VICTORIOUS HAVING ONLY DEALT COLLISION DAMAGE',
			HOTSHOT: 'EMERGE VICTORIOUS HAVING ONLY DEALT RANGED DAMAGE',
			LASTSTAND: 'EMERGE VICTORIOUS WITHOUT MOVING',
			OVERKILL : 'EMERGE VICTORIOUS HAVING DEALT ',
			POWERHOG: 'EMERGE VICTORIOUS WITH ',
			SPEEDDEMON : 'EMERGE VICTORIOUS IN ',
		},
		post: {
			BESTFRIENDS: '',
			BUSHIDO: '',
			GOLDENSTANDARD: '',
			GUTS: '',
			HOTSHOT: '',
			LASTSTAND: '',
			OVERKILL : ' OR MORE, DAMAGE',
			POWERHOG: ' OR MORE, ENERGY STORED IN YOUR CAPACITOR',
			SPEEDDEMON : ' TICKS OR FEWER',
		}
	}
}
export default goalsInfo